version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
     - ./backup/last_backup.sql:/docker-entrypoint-initdb.d/last_backup.sql
      
    environment:
      POSTGRES_DB: doecealumnistudent
      POSTGRES_USER: doecealumnistudentuser
      POSTGRES_PASSWORD: password